setwd("/Volumes/malik_h/user/jayoung/paml_screen/pamlApps")
source("parseAndPlotPAML_functions.R")


######### test the code on an rst file generated by running >1 model at once (an issue uncovered by Tamanash - code used to fail on this)


## test on PAML v 4.8 output
ACE2_sitePAML_rstFile2 <- "data/paml_version_4.8/example_ACE2/M01278_initOmega0.4_codonModel2/rst"
ACE2siteResults2 <- parseRSTfile(ACE2_sitePAML_rstFile2)

## test on PAML v 4.10.6 output
ACE2_sitePAML_rstFile2 <- "data/paml_version_4.10.6/example_ACE2/M01278_initOmega0.4_codonModel2/rst"
ACE2siteResults2 <- parseRSTfile(ACE2_sitePAML_rstFile2)


######### test the code on an rst file from a long gene (an issue uncovered by Jeremy - code used to issue warnings and only consider the first 1000 positions)

# xx still running!

POLA1_sitePAML_rstFile <- "data/paml_version_4.10.6/example_POLA1/M8_initOmega0.4_codonModel2/rst"
POLA1siteResults <- parseRSTfile(POLA1_sitePAML_rstFile)

plotOmegas(POLA1siteResults, 
           title="POLA1 primates: model 8 BEB mean dN/dS estimates", 
           highlightHighBEB=TRUE, 
           highBEBthreshold=0.90, 
           highBEBcolor="red")


######### test the sitewise PAML code on an rst file from branch PAML run - this should FAIL!

ACE2_sitePAML_rstFileBranchPAML <- "data/paml_version_4.10.6/example_ACE2/BRANCHpaml_initOmega0.4_codonModel2/rst"
shouldFail <- parseRSTfile(ACE2_sitePAML_rstFileBranchPAML)


########## branch PAML
ACE2_branchPAML_mlcFile <- "data/paml_version_4.10.6/example_ACE2/BRANCHpaml_initOmega0.4_codonModel2/mlc"

## read in the mlc file from branch PAML. Returns a list with two named elements: 
# 1. 'tree' - the 'w labels' tree
# 2. 'table' - a data.frame containing the table of estimates for each branch. I also do some parsing to help me figure out which nodes/branches are which, and to generate labels for each branch
ACE2branchResults <- parseMLCbranches(ACE2_branchPAML_mlcFile)

## plot the tree, color any label where dN/dS > 1
plotTree(phymlTree=ACE2branchResults[["tree"]], 
         mlcTable=ACE2branchResults[["table"]], 
         labelType="omega_NS",
         myTitle="ACE2 primates: branch PAML", 
         colorHighOmega=TRUE, 
         colorHighOmegaThreshold=1, 
         highOmegaColor="red")

